version: '2.1'

services:
  agrobot-a1-app:
    build: .                    # Builds from your Dockerfile
    privileged: true            # Required for /dev access
    restart: always

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun
      
    network_mode: host
