version: '2.1'

services:
  agrobot-a1-app:
    build: ./AGROBOT-A1-APP
    privileged: true
    restart: always

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun
      
    network_mode: host

  agrobot-a1-phy-v1:
    build: ./V1                   
    privileged: true           
    restart: always

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun
      
    network_mode: host


  agrobot-a1-phy-v2:
    build: ./V2                   
    privileged: true         
    restart: always

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun
      
    network_mode: host

